name: Build and Deploy
on:
  push:
    branches:
      - main
      - ipfs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0

      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1

      - name: Install and Build üîß
        env:
          REACT_APP_SENTRY_DSN: ${{ vars.REACT_APP_SENTRY_DSN }}
          REACT_APP_RPC_URL_1: ${{ vars.REACT_APP_RPC_URL_1 }}
          REACT_APP_RPC_URL_5: ${{ vars.REACT_APP_RPC_URL_5 }}
          REACT_APP_RPC_URL_59140: ${{ vars.REACT_APP_RPC_URL_59140 }}
          REACT_APP_RPC_URL_59144: ${{ vars.REACT_APP_RPC_URL_59144 }}
        run: |
          yarn
          yarn build

      - name: IPFS Deploy üöÄ
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
